### ISSUE TITLE
Submit to fishshell 

### ISSUE THREAD

**Issue by ghost** [bheesham/rust.fish#1]
@bheesham Hi! If you could submit these completions to fish-shell itself (which is the recommended way with the fish shell), that would be great :+1:

**Comment by bheesham** [comment]
AH! Sorry for the really late reply. I already did, and they're in the master branch of the fish-shell repo, see here: [cargo.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/cargo.fish), [rustc.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/rustc.fish).

They're using the "string" feature of fish which isn't yet in a released version, and I'm not sure when the next version is going to land.

The master branch of this repo is meant to work with the currently released version of fish, which at the moment is 2.2.0.

Again, sorry for the late reply.

**Comment by ghost** [comment]
@bheesham Great news! Thanks for letting me know.
